# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# default_platform(:ios)

# platform :ios do
#   desc "Push a new release build to the App Store"
#   lane :release do
#     increment_build_number(xcodeproj: "basetwoecomexpo.xcodeproj")
#     build_app(workspace: "basetwoecomexpo.xcworkspace", scheme: "basetwoecomexpo")
#     upload_to_app_store(skip_metadata: true, skip_screenshots: true)
#   end
# end




default_platform(:ios)

platform :ios do
  desc "Ensure environment variables are loaded"
  before_all do
    dotenv.load
  end

  # Set up the API key for App Store Connect
  def fetch_app_store_connect_api_key
    app_store_connect_api_key(
      key_id: ENV['APP_STORE_CONNECT_API_KEY_ID'],
      issuer_id: ENV['APP_STORE_CONNECT_API_ISSUER_ID'],
      keyfile: ENV['APP_STORE_CONNECT_API_KEY_PATH'],
      in_house: false
    )
  end

  # Create App Identifier and App Store Connect entry
  desc "Create App Identifier and App Store Connect entry"
  lane :create_app_identifier do
    produce(
      app_identifier: ENV['APP_IDENTIFIER'],
      app_name: "Base Two Ecom Expo",
      username: ENV['FASTLANE_USER'],
      team_id: ENV['TEAM_ID']
    )
  end

  # Sync Signing Certificates & Provisioning Profiles using Match
  desc "Set up signing certificates and provisioning profiles"
  lane :setup_signing do
    match(type: "appstore", git_url: ENV['MATCH_GIT_URL'], readonly: false)
  end

  # Build the app for App Store distribution
  desc "Build iOS app"
  lane :build_app do
    gym(
      workspace: "basetwoecomexpo.xcworkspace",
      scheme: "basetwoecomexpo",
      clean: true,
      export_method: "app-store",
      configuration: "Release"
    )
  end

  # Upload to the App Store
  desc "Upload the app to App Store Connect"
  lane :upload_to_app_store do
    api_key = fetch_app_store_connect_api_key

    deliver(
      api_key: api_key,
      app_identifier: ENV['APP_IDENTIFIER'],
      force: true,
      submit_for_review: false,
      automatic_release: false
    )
  end

  # Full Automation - setup signing, build, and upload to App Store
  desc "Fully automated process for building and uploading the app to the App Store"
  lane :deploy_all do
    create_app_identifier
    setup_signing
    build_app
    upload_to_app_store
  end
end
